### ISSUE TITLE
A Small Suggestion

### ISSUE THREAD

**Issue by zhanghongce** [ieee-ceda-datc/RDF-2019#2]
On some OSes, `python` be default refers to python2, which will not work well with the script.
So maybe you can mention one will need python3 for this:
```python ../src/rdf.py --config test.yml --test```

Also, on my end (Ubuntu 18.04), package `libtcl8.5` is needed. Except for that, the test seems running well.

Thanks!

**Comment by jinwookjungs** [comment]
I mentioned that Python 3 and `libtcl8.5` is needed, in `README.md`. Thanks!
